# Generated by Django 5.0.6 on 2024-07-28 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('status', models.CharField(default='in_bag', max_length=50)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='users.reader')),
            ],
        ),
    ]
